"""
QUESTION:
Implement a Python function named `calculate_depth_avg` that takes a 3D array and its depth size as input, calculates the average of all numbers in each depth (z-axis), and returns the averages as a list. The 3D array is generated by a separate function that creates a 3D array of size x X y X z with random numbers from -50 to 50, replaces any prime number with its negative value if it isn't negative already, and returns the array. The function should handle arrays of any size, including cases where x, y, or z is 0.
"""

def calculate_depth_avg(array, z):
    """
    Calculate the average of all numbers in each depth (z-axis) of a 3D array.

    Args:
        array (list): A 3D array of numbers.
        z (int): The depth size of the array.

    Returns:
        list: A list of averages for each depth.
    """
    depth_avgs = []
    for k in range(z):
        total_sum = 0
        count = 0
        for row in array:
            for elem in row:
                if k < len(elem): # To avoid index out of range error
                    total_sum += elem[k]
                    count += 1
        if count > 0: # To avoid division by zero error
            depth_avgs.append(total_sum / count)
        else:
            depth_avgs.append(0) # Return 0 if all depths are empty
    return depth_avgs