"""
QUESTION:
Write a function `calculate_area(length, width)` that calculates the area of a rectangle and create a test suite that achieves a minimum code coverage of 90%. The test suite should be able to kill at least 90% of the mutants generated by a mutation testing tool.
"""

def calculate_area(length, width):
    return length * width