"""
QUESTION:
Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair of elements from the array.
Note: AND is bitwise '&' operator. 
Example 1:
Input : Arr[] = {4, 8, 12, 16}
Output : 8
Explanation:
Pair (8,12) has the Maximum AND Value
i.e. 8.
Example 2:
Input : Arr[] = {4, 8, 16, 2} 
Output : 0
Your Task:
The input is already taken care of by the driver code. You only need to complete the function maxAND() that takes an array (arr), size of Array (n) as parameter and return the maximum AND value of pair. The driver code takes care of the printing.
Expected Time Complexity: O(N).
Expected Auxiliary Space: O(1).
Constraints:
1 <= N <= 5*10^{5}
1 <= arr[i] <= 5*10^{5}
"""

def max_and_value(arr, n):
    ans = 0
    for i in range(18, -1, -1):
        temp = []
        for a in arr:
            if a & 1 << i:
                temp.append(a)
        if len(temp) == 2:
            return temp[0] & temp[1]
        elif len(temp) > 2:
            arr = temp
            ans += 1 << i
    return ans