"""
QUESTION:
Create a function called `wind_power` that takes three parameters: air density in kg/m^3, rotor area in m^2, and wind velocity in m/s. The function should return the power generated by a wind turbine in Watts, calculated using the formula: Power = 0.5 * air density * rotor area * wind velocity^3.
"""

import math

def wind_power(density, area, velocity):
    power = 0.5 * density * area * math.pow(velocity, 3)
    return power