"""
QUESTION:
Given a sequence where each number is obtained by multiplying the previous number by 2 and then adding 2, write a function `generate_next_number` that takes the last number in the sequence as input and returns the next number in the sequence. The sequence starts with 2 and each subsequent number is generated by the formula `next_number = previous_number * 2 + 2`.
"""

def generate_next_number(previous_number):
    """
    Generate the next number in the sequence.

    Args:
    previous_number (int): The last number in the sequence.

    Returns:
    int: The next number in the sequence.
    """
    return previous_number * 2 + 2