"""
QUESTION:
PRAVAH, an annual techfest is being organised at SKIT. Naina comes up with an idea for an event Guess The Number. In this event, the computer thinks up a random number and the player is asked to guess that number and enter it in the system. if the number is correct, the player wins.

Rakesh, a student who is good at hacking finds a breach in the system and has got the access the modify any 1 digit of the guessed number, but this access is only granted after the number has been entered by a player. 

So, at the event, the computer thinks of a number A, a friend of Rakesh enters a number B and Rakesh changes one digit of the number A, so that his friend wins. You are given two integers A and B. Print "wins" if there is a possibility that the friend will win by changing of a digit, otherwise, print "loses". If the numbers A and B are same print "wins".

Input

First line of input contains the number generated by system.

Second line of input contains the number entered by player.

Output

A single word "wins" or "loses"

Constraints

1 ≤ A ≤ 900000

1 ≤ B ≤ 900000

Number of digits of A = Number of digits of B

Sample Input 1

1111

1011

Sample Output 1

wins

Sample Input 2

108

110

Sample Output 2

loses

SAMPLE INPUT

SAMPLE OUTPUT
"""

def can_win_by_changing_one_digit(A: int, B: int) -> str:
    # Convert the numbers to strings for easy comparison
    str_A = str(A)
    str_B = str(B)
    
    # Check if the lengths of the numbers are the same
    if len(str_A) != len(str_B):
        return 'loses'
    
    # Count the number of differing digits
    differing_digits = 0
    for i in range(len(str_A)):
        if str_A[i] != str_B[i]:
            differing_digits += 1
    
    # Determine if the player can win
    if differing_digits == 1 or differing_digits == 0:
        return 'wins'
    else:
        return 'loses'