"""
QUESTION:
Define a function named `wind_power` that calculates the power generated by a wind turbine. The function should take three parameters: air density (`density`), rotor area (`area`), and wind velocity (`velocity`). The function should return the calculated power using the formula: Power = 0.5 * air density * rotor area * wind velocity^3.
"""

import math
def wind_power(density, area, velocity):
    power = 0.5 * density * area * math.pow(velocity, 3)
    return power