"""
QUESTION:
Write a function `generate_isbn` that takes four parameters: `author_last_name`, `book_title`, `publisher_name`, and `publication_year`, and returns a 10-digit ISBN number. The ISBN number should be generated by combining elements from the input parameters in a specific order and calculating a checksum digit. 

The elements are: 
- the first three letters of the author's last name (padded with 'X' if necessary) in uppercase, 
- the first three letters of the book title (padded with 'X' if necessary) in uppercase, 
- the first letter of the publisher's name in uppercase, 
- and the last two digits of the publication year. 

The checksum digit is calculated by multiplying each character in the concatenated string by its position, summing them up, taking the result modulo 11, and replacing the remainder 10 with 'X'. The checksum digit is then appended to the end of the concatenated string.
"""

def generate_isbn(author_last_name, book_title, publisher_name, publication_year):
    author_initials = author_last_name[:3].upper().ljust(3, 'X')
    title_initials = book_title[:3].upper().ljust(3, 'X')
    publisher_initial = publisher_name[0].upper()
    year_digits = publication_year[-2:]
    
    isbn_number = author_initials + title_initials + publisher_initial + year_digits
    
    checksum = 0
    for i, digit in enumerate(isbn_number):
        position = i + 1
        if digit.isalpha():
            value = ord(digit) - ord('A') + 10
        else:
            value = int(digit)
        checksum += position * value
    checksum %= 11
    if checksum == 10:
        checksum_digit = 'X'
    else:
        checksum_digit = str(checksum)
        
    isbn_number += checksum_digit
    
    return isbn_number