"""
QUESTION:
A special type of prime is generated by the formula `p = 2^m * 3^n + 1` where `m` and `n` can be any non-negative integer.

The first `5` of these primes are `2, 3, 5, 7, 13`, and are generated as follows: 
```Haskell
2 = 2^0 * 3^0 + 1
3 = 2^1 * 3^0 + 1
5 = 2^2 * 3^0 + 1
7 = 2^1 * 3^1 + 1
13 = 2^2 * 3^1 + 1
..and so on
```
You will be given a range and your task is to return the number of primes that have this property. For example, `solve(0,15) = 5`, because there are only `5` such primes `>= 0 and < 15`; they are `2,3,5,7,13`. The upper limit of the tests will not exceed `1,500,000`.

More examples in the test cases. 

Good luck!

If you like Prime Katas, you will enjoy this Kata: [Simple Prime Streaming](https://www.codewars.com/kata/5a908da30025e995880000e3)
"""

def count_special_primes_in_range(start: int, end: int) -> int:
    sb_primes = [
        2, 3, 5, 7, 13, 17, 19, 37, 73, 97, 109, 163, 193, 257, 433, 487, 577, 
        769, 1153, 1297, 1459, 2593, 2917, 3457, 3889, 10369, 12289, 17497, 
        18433, 39367, 52489, 65537, 139969, 147457, 209953, 331777, 472393, 
        629857, 746497, 786433, 839809, 995329, 1179649, 1492993
    ]
    
    return sum(1 for p in sb_primes if start <= p < end)