"""
QUESTION:
Define a function `wind_power` that takes in three parameters: air density, rotor area, and wind velocity, and returns the power generated by a wind turbine. The function should use the formula: Power = 0.5 * air density * rotor area * wind velocity^3. The input values are in the following units: air density in kg/m^3, rotor area in m^2, and wind velocity in m/s. The output should be in Watts.
"""

import math
def wind_power(density, area, velocity):
    power = 0.5 * density * area * math.pow(velocity, 3)
    return power