"""
QUESTION:
Given two integers n and k, return the kth lexicographical combination sequence from the set [1, 2, ..., n] of length k. The combination sequence is generated by listing and labeling all combinations in order. 

Restrictions: 
1 <= n <= 9 
1 <= k <= nCk
"""

from math import factorial, floor, prod
from itertools import permutations

def getKthPermutation(n, k):
    numbers = list(range(1, n + 1))
    permutation = ''
    k -= 1

    while n > 0:
        n -= 1
        index = k // factorial(n)
        k %= factorial(n)
        permutation += str(numbers[index])
        numbers.remove(numbers[index])

    return permutation