"""
QUESTION:
Construct a function named `count_and_convert` that takes an integer `start` as a parameter, counts from `start` to 10 (inclusive) but only iterates over even numbers, and prints each even number in both decimal and binary formats. The function should also return the sum of all the even numbers generated by the loop.
"""

def count_and_convert(start):
    total = 0
    for i in range(start, 11, 2):
        total += i
        print(f"{i} in decimal is {i:d} and in binary is {bin(i)}")
    return total