"""
QUESTION:
Write a Python function `count_valid_ipv4` that takes a string `ip` as input representing an IPv4 address, and returns the number of valid IPv4 addresses that can be generated by changing exactly one digit in the input address. The function should first check if the input string is a valid IPv4 address, which consists of four parts separated by dots, each part being a number between 0 and 255. If the input string is a valid IPv4 address, the function should try each possible digit (0-9) for each part and count the number of modified addresses that are also valid IPv4 addresses (excluding the original address).
"""

def count_valid_ipv4(ip):
    count = 0
    parts = ip.split('.')
    for i in range(len(parts)):
        original_part = parts[i]
        for j in range(10):
            new_part = str(j)
            if original_part != new_part:
                parts[i] = new_part
                if len(parts) == 4 and all(part.isdigit() and 0 <= int(part) <= 255 for part in parts):
                    count += 1
        parts[i] = original_part
    return count