"""
QUESTION:
Implement a function `minPatches(nums, n)` that takes a sorted array of integers `nums` and an integer `n` as input, and returns the least number of patches required to append or patch elements to the array such that any integer within the inclusive range `[1, n]` can be generated by the summation of certain elements within the array.

Constraints: `1 <= len(nums) <= 1000`, `1 <= nums[i] <= 10^4`, `nums` is sorted in ascending order, and `1 <= n <= 2^31 - 1`.
"""

def minPatches(nums, n):
    patch, i, cover = 0, 0, 0
    while cover < n:
        if i < len(nums) and nums[i] <= cover + 1:
            cover += nums[i]
            i += 1
        else:
            cover += cover + 1
            patch += 1
    return patch