"""
QUESTION:
Create a function `wind_power` that calculates the power generated by a wind turbine. The function should take three parameters: `density` (air density in kg/m^3), `area` (rotor area in m^2), and `velocity` (wind velocity in m/s), and return the calculated power in Watts.
"""

import math
def wind_power(density, area, velocity):
    power = 0.5 * density * area * math.pow(velocity, 3)
    return power