"""
QUESTION:
Create a function called `generate_nickname` that takes in three parameters: `george_name`, `birth_year`, and `favorite_color`. The function should return a nickname generated by combining the first two letters of `george_name`, the last two digits of `birth_year`, and the first two letters of `favorite_color`. The nickname should be in the format of string.
"""

def generate_nickname(george_name, birth_year, favorite_color):
    nickname = george_name[:2] + str(birth_year)[-2:] + favorite_color[:2]
    return nickname