"""
QUESTION:
Given a sequence generated by substituting 0 with 01 and 1 with 10 in each subsequent sequence, find the K-th symbol in the N-th sequence. The values of K are 1-indexed. Write a function `kthGrammar(N, K)` where N is an integer within the range [1, 30] and K is an integer within the range [1, 2^(N-1)].
"""

def kthGrammar(N, K):
    if K == 1:
        return 0
    if K % 2 == 0:
        return 1 - kthGrammar(N-1, K//2)
    else:
        return kthGrammar(N-1, (K+1)//2)