"""
QUESTION:
Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair(arr_{i, }arr_{j}) from the array such that i != j.
Note: AND is bitwise '&' operator. 
Example 1:
Input: 
N = 4
arr[] = {4, 8, 12, 16}
Output: 8
Explanation:
Pair (8,12) has the Maximum AND Value 8.
Example 2:
Input:
N = 4
arr[] = {4, 8, 16, 2}
Output: 0
Explanation: Any two pairs of the array has 
Maximum AND Value 0.
Your Task: 
You don't need to read input or print anything. Your task is to complete the function maxAND() which takes the array elements and N (size of the array) as input parameters and returns the maximum AND value generated by any pair in the array. 
Expected Time Complexity: O(N * log M), where M is the maximum element of the array.
Expected Auxiliary Space: O(1).
Constraints:
1 <= N <= 10^{5}
1 <= arr[i] <= 10^{5}
"""

def check_bit(pattern, arr, n):
    count = 0
    for i in range(n):
        if pattern & arr[i] == pattern:
            count += 1
    return count

def max_and_value(arr, n):
    res = 0
    for bit in range(16, -1, -1):
        count = check_bit(res | 1 << bit, arr, n)
        if count >= 2:
            res |= 1 << bit
    return res