"""
QUESTION:
Create a function `generate_migration_script(operations)` that takes a list of migration operations and returns a string representing a migration script. Each operation is a dictionary with the keys "operation_type", "table_name", and "fields". The function should generate a migration script that handles "create_table" and "add_field" operations. The script should be in the format of a Django migration script. The function should handle multiple operations and fields, and the output should include the necessary import statements and class structure.
"""

def generate_migration_script(operations):
    script = "# -*- coding: utf-8 -*-\n"
    script += "# Generated by CustomMigrationTool 1.0\n"
    script += "from __future__ import unicode_literals\n\n"
    script += "from django.db import migrations, models\n\n"
    script += "class Migration(migrations.Migration):\n\n"
    script += "    dependencies = [\n"
    script += "        ('app_name', 'previous_migration'),\n"  
    script += "    ]\n\n"
    script += "    operations = [\n"

    for operation in operations:
        if operation["operation_type"] == "create_table":
            script += f"        migrations.CreateModel(\n"
            script += f"            name='{operation['table_name']}',\n"
            script += f"            fields=[\n"
            for field in operation["fields"]:
                script += f"                ('{field['name']}', {field['type']}),\n"
            script += "            ],\n"
            script += "        ),\n"
        elif operation["operation_type"] == "add_field":
            script += f"        migrations.AddField(\n"
            script += f"            model_name='{operation['table_name']}',\n"
            script += f"            name='{operation['fields'][0]['name']}',\n"
            script += f"            field={operation['fields'][0]['type']},\n"
            script += "        ),\n"

    script += "    ]\n"

    return script