"""
QUESTION:
Write a function named `generate_fibonacci` that generates the first n Fibonacci numbers after a specified starting number. The Fibonacci sequence is generated by starting with the given number, and each subsequent number is the sum of the two preceding ones. For this problem, the starting number is 1 and n is 8.
"""

def generate_fibonacci(n):
    """
    Generates the first n Fibonacci numbers after a specified starting number.

    Args:
        n (int): The number of Fibonacci numbers to generate.

    Returns:
        list: A list of the first n Fibonacci numbers.
    """
    fib_sequence = [1, 1]
    while len(fib_sequence) < n:
        fib_sequence.append(fib_sequence[-1] + fib_sequence[-2])
    return fib_sequence