"""
QUESTION:
Write a function called `CustomMiddleware` that will be executed for every Django view, allowing you to add custom information to the request. The function should be able to modify the request before it reaches the view and the response after it is generated by the view. The function should be able to be added to the Django settings for global execution.
"""

def CustomMiddleware(get_response):
    def middleware(request):
        # Code to be executed for each request before
        # the view (and later middleware) are called.

        request.some_info = 'Information'

        response = get_response(request)

        # Code to be executed for each request/response after
        # the view is called.

        return response

    return middleware