"""
QUESTION:
Implement a class `Authenticator` with methods `validate` and `logout`. The `validate` method should accept a token, return the response generated by `auth_is_valid` with a 200 status code and "Token is valid" message if the token is valid, and a 401 status code and "Invalid token" message otherwise. The `logout` method should invalidate the provided token and return the response generated by `auth_logout` with a 200 status code and "Logout successful" message if the token is valid, and a 401 status code and "Invalid token" message otherwise. The authentication tokens should be securely stored and managed within the `Authenticator` class.
"""

import secrets

def auth_is_valid(status_code, message, token):
    return {"status_code": status_code, "message": message, "token": token}

def auth_logout(status_code, message, token):
    return {"status_code": status_code, "message": message, "token": token}

class Authenticator:
    def __init__(self):
        self.valid_tokens = set()

    def validate(self, token):
        if token in self.valid_tokens:
            return auth_is_valid(200, "Token is valid", token)
        else:
            return auth_is_valid(401, "Invalid token", "")

    def logout(self, token):
        if token in self.valid_tokens:
            self.valid_tokens.remove(token)
            return auth_logout(200, "Logout successful", token)
        else:
            return auth_logout(401, "Invalid token", "")