"""
QUESTION:
Write a function named `wind_power` to calculate the power generated by a wind turbine. The function should take in three parameters: air density in kg/m^3, rotor area in m^2, and wind velocity in m/s, and return the calculated power in Watts. The power should be calculated using the formula: Power = 0.5 * air density * rotor area * wind velocity^3.
"""

import math
def wind_power(density, area, velocity):
    power = 0.5 * density * area * math.pow(velocity, 3)
    return power