"""
QUESTION:
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

def find_added_letter(s: str, t: str) -> str:
    """
    Finds the letter that was added to string `t` which is a shuffled version of string `s` with one additional letter.

    Parameters:
    - s (str): The original string.
    - t (str): The shuffled string with one additional letter.

    Returns:
    - str: The letter that was added to `t`.
    """
    sum_s = sum(ord(char) for char in s)
    sum_t = sum(ord(char) for char in t)
    return chr(sum_t - sum_s)