"""
QUESTION:
Implement the `make_staggered_quads` function, which takes in a grayscale image `gt`, a binary mask `gt_hist` derived from the histogram of `gt`, and two integer parameters `quad_size` and `step_size`. The function returns a list of non-empty quads, represented as tuples of (x, y, width, height), where x and y are the coordinates of the top-left corner, and width and height are the size of the quad. The `make_staggered_quads` function should check for non-empty quads by verifying that the sum of the corresponding region in `gt_hist` is greater than 0. Also, implement the `count_non_empty_quads` function, which returns the number of non-empty quads generated by the `make_staggered_quads` function. 

Input:
- `gt` (2D numpy array): A grayscale image.
- `gt_hist` (2D numpy array): A binary mask derived from the histogram of `gt`.
- `quad_size` (int): The size of the quads to be created.
- `step_size` (int): The step size for staggering the quads.

Output:
- For `make_staggered_quads` function: A list of non-empty quads represented as tuples of (x, y, width, height).
- For `count_non_empty_quads` function: The number of non-empty quads generated.
"""

import numpy as np
from typing import List, Tuple

def make_staggered_quads(gt: np.ndarray, gt_hist: np.ndarray, quad_size: int, step_size: int) -> List[Tuple[int, int, int, int]]:
    non_empty_quads = []
    height, width = gt.shape
    for y in range(0, height - quad_size + 1, step_size):
        for x in range(0, width - quad_size + 1, step_size):
            if np.sum(gt_hist[y:y+quad_size, x:x+quad_size]) > 0:
                non_empty_quads.append((x, y, quad_size, quad_size))
    return non_empty_quads

def count_non_empty_quads(gt: np.ndarray, gt_hist: np.ndarray, quad_size: int, step_size: int) -> int:
    return len(make_staggered_quads(gt, gt_hist, quad_size, step_size))