"""
QUESTION:
Write a function `match_brackets(lst)` that takes a list of strings containing parentheses '(', ')', square brackets '[', ']', and curly braces '{', '}' as input. The function should return True if a valid nested structure can be generated by concatenating the input strings, and False otherwise. The function should handle conversion of empty strings and individual pairs into valid layouts.
"""

def match_brackets(lst):
    pair = {
        ')': '(',
        ']': '[',
        '}': '{'
    }

    stack = []
    for symbol in ''.join(lst):
        if symbol in pair.values():    # Open bracket
            stack.append(symbol)
        elif symbol in pair.keys():    # Close bracket
            if stack == [] or pair[symbol] != stack.pop():
                return False
    return stack == []