"""
QUESTION:
Implement a function called generate_range(start, end, step) that generates a list of numbers from start to end with a specified step using recursion. Implement two additional functions: calculate_sum_of_squares and calculate_even_square_sum. The calculate_sum_of_squares function should recursively calculate the sum of the squares of all odd numbers in the range generated by the generate_range function, and the calculate_even_square_sum function should recursively calculate the sum of the squares of all even numbers in the range.
"""

def generate_range(start, end, step):
    """Generate a list of numbers from start to end with a specified step using recursion."""
    if start > end:
        return []
    return [start] + generate_range(start + step, end, step)


def calculate_sum_of_squares(numbers):
    """Recursively calculate the sum of the squares of all odd numbers in the range."""
    if not numbers:
        return 0
    if numbers[0] % 2 != 0:
        return numbers[0] ** 2 + calculate_sum_of_squares(numbers[1:])
    return calculate_sum_of_squares(numbers[1:])


def calculate_even_square_sum(numbers):
    """Recursively calculate the sum of the squares of all even numbers in the range."""
    if not numbers:
        return 0
    if numbers[0] % 2 == 0:
        return numbers[0] ** 2 + calculate_even_square_sum(numbers[1:])
    return calculate_even_square_sum(numbers[1:])