"""
QUESTION:
Calculate the total multinomial loss for a batch of recommendations generated by a model. 

Implement a function `calculate_multinomial_loss(recon_batch, group_items)` that takes in two parameters:
- `recon_batch` (list of lists): A 2D list representing the batch of recommendations, where each inner list contains probabilities of items being recommended for a particular user.
- `group_items` (list of integers): A list representing the actual items preferred by the group of users.

The function should return the total multinomial loss as a floating-point number.
"""

import numpy as np

def multinomial_loss(recon_batch, group_items):
    eval_loss = 0.0
    for i in range(len(recon_batch)):
        loss = -np.log(recon_batch[i][group_items[i] - 1])
        eval_loss += loss
    return eval_loss