"""
QUESTION:
Create a function `nth_term(n)` that takes a positive integer `n` as input and returns the nth term in a series generated by the summation of the preceding pair of even integers.
"""

def nth_term(n):
    return n * (n - 1)