"""
QUESTION:
Create a function `wind_power` that calculates the power generated by a wind turbine. The function should take three parameters: `density`, `area`, and `velocity`, representing the air density in kg/m^3, the rotor area in m^2, and the wind velocity in m/s, respectively. The function should return the power generated by the wind turbine in Watts, calculated using the formula: Power = 0.5 * air density * rotor area * wind velocity^3.
"""

import math

def wind_power(density, area, velocity):
    """
    Calculate the power generated by a wind turbine.

    Parameters:
    density (float): Air density in kg/m^3
    area (float): Rotor area in m^2
    velocity (float): Wind velocity in m/s

    Returns:
    float: Power generated by the wind turbine in Watts
    """
    power = 0.5 * density * area * math.pow(velocity, 3)
    return power