"""
QUESTION:
Write a function `collatz(n)` that generates the Collatz sequence starting from a positive integer `n` until it reaches 1. The sequence is generated by repeatedly applying the following rules: if `n` is even, divide it by 2, and if `n` is odd, multiply it by 3 and add 1.
"""

def collatz(n):
    sequence = [n]
    while n != 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = n * 3 + 1
        sequence.append(n)
    return sequence