"""
QUESTION:
Write a function named `sequence_length` that takes an integer `n` and returns the length of the sequence generated by iteratively applying the following rules: if `n` is even, `n` becomes `n/2`, and if `n` is odd, `n` becomes `3n + 1`. The sequence ends when `n` becomes 1. 

Use this function to find the initial number less than one million that generates the longest sequence, and return this number.
"""

def sequence_length(n):
    count = 1
    while n != 1:
        if n % 2 == 0:
            n = n / 2
        else:
            n = 3*n + 1
        count += 1
    return count