"""
QUESTION:
Create a function `sum_prime_numbers(n, obstacles)` that calculates the sum of all prime numbers present in the series generated by the number of ways to climb `n` stairs, where you can climb 1, 2, or 3 stairs at a time and there are obstacles given as a 1D boolean array `obstacles` where `True` indicates an obstacle and `False` indicates no obstacle. The function should not consider the stairs with obstacles and it is guaranteed that the bottom and top stair will never be obstructed.
"""

def is_prime(n): 
    if (n <= 1) : 
        return False
    if (n <= 3) : 
        return True
    if (n % 2 == 0 or n % 3 == 0) : 
        return False
    i = 5
    while(i * i <= n) : 
        if (n % i == 0 or n % (i + 2) == 0) : 
            return False
        i = i + 6
    return True

def sum_prime_numbers(n, obstacles):
    s = [0]*(n+1)
    
    if not obstacles[0]:
        s[0] = 1
    if n > 1 and not obstacles[1]:
        s[1] = 2
    if n > 2 and not obstacles[2]:
        s[2] = 4

    for i in range(3, n+1):
        if not obstacles[i]:
            s[i] = s[i-1]+s[i-2]+s[i-3]

    sum_primes = 0
    for i in s:
        if is_prime(i):
            sum_primes += i
    return sum_primes