"""
QUESTION:
Write a function `get_city_revenue(city_name)` that takes a city name as input and returns the total revenue generated by that city in AUD. The function should return an error message if the city name is not found in the table, and a message if the city name is valid but the revenue is not available. The revenue table is: "Sydney": $10000, "Melbourne": $7500, "Brisbane": $5000, "Adelaide": $9000.
"""

def get_city_revenue(city_name):
    revenue_table = {
        "Sydney": 10000,
        "Melbourne": 7500,
        "Brisbane": 5000,
        "Adelaide": 9000
    }

    if city_name in revenue_table:
        return f"The total revenue generated by {city_name} is ${revenue_table[city_name]}."
    else:
        return f"Sorry, {city_name} is not a valid city name in the table."