"""
QUESTION:
Create a function called `decode_cyclic` that takes an encoded string `s` as input and returns the decoded string. The encoded string is created by the `encode_cyclic` function which obfuscates the original text by rotating subgroups of three characters and also supports numeric character references. The `decode_cyclic` function should reverse this process to retrieve the original text. It should handle cases where the input string contains isolated characters and numeric character references in the format `&#...;`.
"""

def decode_cyclic(s: str):
    """
    This algorithm is designed to inverse an obfuscated text string and numeric character references that has been generated by the encode_cyclic method.
    """
    groups = [s[i: i + 3] for i in range(0, len(s), 3)]
    groups = [(group[-1] + group[:-1]) if len(group) == 3 else group for group in groups]
    
    # Convert back encoded numeric character references to characters
    for i in range(len(groups)):
        if groups[i].startswith('&#') and groups[i].endswith(';'):
            groups[i] = chr(int(groups[i][2:-1]))
            
    return "".join(groups)