"""
QUESTION:
Create a function `magicalString(n)` that returns the number of '1's in the first `n` numbers of the magical string `S`, which consists of '1', '2', and '3', where the string `S` is generated by concatenating the number of contiguous occurrences of characters '1', '2', and '3'. The function should be able to handle inputs where `n` is up to 1,000,000.
"""

def magicalString(n):
    if n <= 0:
        return 0
    elif n <= 3:
        return 1
    queue = [1,2,2]
    magic = '122'
    index = 2
    while len(magic) < n:
        if queue[0] == 1:
            if magic[-1] == '1':
                magic += '2'
                queue.append(2)
            else:
                magic += '1'
                queue.append(1)
        else:
            if magic[-1] == '1':
                magic += '22'
                queue.append(2)
                queue.append(2)
            else:
                magic += '11'
                queue.append(1)
                queue.append(1)
        queue = queue[1:]
    return magic[:n].count('1')