"""
QUESTION:
Write a function `get_city_revenue(city_name)` that accepts a city name as input and returns the total revenue generated by that city in AUD. The function should first check if the city name exists in the table. If it does, it should then check if revenue data for that city is available. If the city name is not found in the table, or if the revenue data is not available, the function should return an error message. The table is represented as a dictionary with city names as keys and dictionaries containing revenue data as values.
"""

def get_city_revenue(city_table, city_name):
    # Check if the city name exists in the table
    if city_name in city_table:
        # If the city exists, check if revenue data is available
        if 'Revenue' in city_table[city_name]:
            # If revenue data is available, output the revenue in AUD
            return f"The revenue for {city_name} is AUD {city_table[city_name]['Revenue']}"
        else:
            # If revenue data is not available, output an error message
            return f"Error: Revenue data not available for {city_name}"
    else:
        # If the city does not exist, output an error message
        return f"Error: {city_name} not found in table"