"""
QUESTION:
Implement a function `fibonacci(n)` to generate a Fibonacci sequence of length `n` using recursion. The function should return the Fibonacci sequence as a list. Additionally, implement a function `sum_fibonacci(seq)` to calculate the sum of all elements in the Fibonacci sequence. The input `seq` for `sum_fibonacci(seq)` is the Fibonacci sequence generated by `fibonacci(n)`. The sequence should start from 0 and 1.
"""

def fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        seq = fibonacci(n-1)
        seq.append(seq[-1] + seq[-2])
        return seq

def sum_fibonacci(seq):
    return sum(seq)