"""
QUESTION:
Write a function `generate_collatz_sequence(n)` that generates the Collatz sequence starting from a positive integer `n` (less than 1,000,000) up to 1 and returns the number of steps and a boolean indicating whether the sequence includes an even number. The Collatz sequence is generated by applying the following rules: if `n` is even, divide it by 2; if `n` is odd, multiply it by 3 and add 1.
"""

def generate_collatz_sequence(n):
    steps = 0
    is_even_included = False
    while n != 1:
        if n % 2 == 0:
            n = n // 2
            is_even_included = True
        else:
            n = n * 3 + 1
        steps += 1
    return steps, is_even_included