"""
QUESTION:
Create a recursive function `recursive_sum` to calculate the sum of all prime numbers between two given numbers, `start` and `end`. The function should utilize a boolean list of prime numbers generated by the `sieve_of_eratosthenes` function, which implements the Sieve of Eratosthenes algorithm to identify prime numbers up to a given `limit`. The `recursive_sum` function should take `start`, `end`, and the boolean list of primes as parameters, and return the sum of all prime numbers in the range.
"""

def recursive_sum(start, end, primes, total=0):
    if start > end:
        return total
    elif primes[start]:
        return recursive_sum(start + 1, end, primes, total + start)
    else:
        return recursive_sum(start + 1, end, primes, total)