"""
QUESTION:
Create a function called `collatz` that takes an integer `n` as input and returns a list representing the Collatz sequence starting from `n`. The Collatz sequence is generated by repeatedly applying the following operations: if `n` is even, divide it by 2, otherwise multiply it by 3 and add 1. The sequence ends when `n` becomes 1.
"""

def collatz(n):
    sequence = [n]
    while n != 1:
        if n % 2 == 0:
            n = n / 2
        else:
            n = 3 * n + 1
        sequence.append(n)
    return sequence