"""
QUESTION:
Write a function `calculate_area(length, width)` that calculates the area of a rectangle given its length and width, and create a test suite that achieves a minimum code coverage of 90% using mutation testing with `mutmut` and `pytest`. The test suite should be able to kill all mutations generated by `mutmut`.
"""

def calculate_area(length, width):
    return length * width