"""
QUESTION:
Create a Python function `extract_info` that takes a string `source_code` as input and returns a dictionary containing the author and version information extracted from a comment block in the source code. The comment block is expected to be in the format:

```
/**
@author author_name
@detail Automatically generated by tool_name version_number
**/
```

The function should return a dictionary with keys 'author' and 'version' if the comment block is in the expected format, otherwise it should return `None`. The version number is expected to be in the format `x.x.x` where `x` is a digit.
"""

import re

def extract_info(source_code: str) -> dict:
    pattern = r'/\*\*\s*@author\s+(.*?)\s+@detail\s+Automatically generated by\s+(\S+)\s+(\d+\.\d+\.\d+)\s+\*/'
    match = re.search(pattern, source_code, re.DOTALL)
    if match:
        author = match.group(1)
        tool = match.group(2)
        version = match.group(3)
        return {'author': author, 'version': version}
    else:
        return None