"""
QUESTION:
Write a function `generate_migration_script` that generates a migration script for a hypothetical database migration tool in the format used by Django's migration system. The function takes a list of database table names as input and returns a string representing the migration script. The migration script should include a Django migration class with the necessary `operations` to create the specified tables, including an auto-incrementing primary key 'id' for each table. The function should not include any additional fields for the tables beyond the 'id' field.
"""

def generate_migration_script(table_names):
    migration_script = f"# Generated by Django 2.2.1 on 2019-05-08 14:56\n\n"
    migration_script += "from django.db import migrations, models\n\n"
    migration_script += "class Migration(migrations.Migration):\n"
    migration_script += "    dependencies = []\n\n"
    migration_script += "    operations = [\n"

    for table_name in table_names:
        migration_script += f"        migrations.CreateModel(\n"
        migration_script += f"            name='{table_name}',\n"
        migration_script += f"            fields=[\n"
        migration_script += f"                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\n"
        migration_script += f"            ],\n"
        migration_script += f"        ),\n"

    migration_script += "    ]\n"

    return migration_script