"""
QUESTION:
Implement the function `prime_sequence_length(a, b)` that calculates the maximum number of consecutive prime numbers generated by the equation `n^2 + an + b` where `n` starts at 0 and increments by 1, until a non-prime number is encountered. The function should take two integers `a` and `b` as input and return the length of the prime sequence.
"""

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

def prime_sequence_length(a, b):
    n = 0
    while True:
        num = n ** 2 + a * n + b
        if not is_prime(num):
            return n
        n += 1