"""
QUESTION:
Create two functions, `fibonacci(n)` and `is_in_fibonacci(n, num)`. The `fibonacci(n)` function should generate and return the Fibonacci sequence up to the nth term. The `is_in_fibonacci(n, num)` function should check if a given number `num` exists in the Fibonacci sequence generated by `fibonacci(n)`.
"""

def fibonacci(n):
    fib_seq = [0, 1]
    while len(fib_seq) < n:
        fib_seq.append(fib_seq[-1] + fib_seq[-2])
    return fib_seq

def is_in_fibonacci(n, num):
    fib_seq = fibonacci(n)
    return num in fib_seq