"""
QUESTION:
Create a function `nth_value(n)` to calculate the nth value in a sequence where each number is the sum of the two preceding even numbers. However, given that the sequence can be generated by simply doubling the preceding even number, implement this logic recursively. The sequence starts with 0 and 2 for n=1 and n=2 respectively, and for n>2, each term is twice the preceding term.
"""

def nth_value(n):
    if n == 1:
        return 0
    elif n == 2:
        return 2
    else:
        return 2 * nth_value(n-1)