"""
QUESTION:
Create a function generate_username that takes first_name and last_name as input, and returns a unique username that is at least six characters long and only contains alphanumeric characters. The username should be generated by combining the first and last name. If the username is shorter than six characters, it should be padded with its length. If the username already exists, a number should be appended to the end to make it unique.
"""

def generate_username(first_name, last_name, existing_usernames={}):
    # create username by combining first and last name
    username = first_name.lower() + last_name.lower()
    # remove any non-alphanumeric characters from username
    username = ''.join(e for e in username if e.isalnum())
    # add a number to username if it's shorter than six characters
    if len(username) < 6:
        username += str(len(username))
    # check if username already exists, if so add a number to make it unique
    original_username = username
    n = 1
    while username in existing_usernames:
        username = original_username + str(n)
        n += 1
    # add new username to set of all usernames and return it
    existing_usernames[username] = True
    return username