"""
QUESTION:
During Quarantine Time Chef is at home and he was quite confused about what to cook so, he went to his son and asked about what would he prefer to have? He replied, cakes.
Now, chef cook $N$ number of cake and number of layers for every cake is different. After cakes are baked, Chef arranged them in a particular order and then generates a number by putting number of layers of cakes as digit in sequence (e.g., if chef arranges cakes with layers in sequence $2$, $3$ and $5$ then generated number is $235$).
Chef has to make his son powerful in mathematics, so he called his son and ask him to arrange the cakes in all the possible ways and every time when different sequence is generated he has to note down the number. At the end he has to find sum of all the generated numbers. So, help him to complete this task.

-----Input:-----
- First line will contain $T$, number of testcases. Then the testcases follow. 
- The first line of each test case contains a single integer $N$ denoting number of cakes.
- The second line contains $N$ space-separated integers $L1$ $L2$ … $LN$ layers of the cake.

-----Output:-----
For each test case, print a single line containing sum of all the possible numbers which is generated by arranging cake in different sequence.

-----Constraints :-----
- $1 \leq T  \leq 2*10^5$
- $1 \leq N, L1, L2, L3,…, LN \leq 9$

-----Sample Input:-----
1
3
2 3 5

-----Sample Output:-----
2220

-----Explanation:-----
Sum of all possibilities :
$235 + 532 + 253 + 352 + 523 + 325 = 2220 $
"""

from math import factorial

def calculate_cake_layer_sum(test_cases, cake_layers_list):
    results = []
    
    for i in range(test_cases):
        n = len(cake_layers_list[i])
        sum1 = 0
        final_sum = 0
        num = cake_layers_list[i]
        rep_time = factorial(n - 1)
        rep_count = {}
        
        for layer in num:
            if layer in rep_count:
                rep_count[layer] += 1
            else:
                rep_count[layer] = 1
        
        for layer in rep_count:
            if rep_count[layer] == 1:
                sum1 += layer * factorial(n - rep_count[layer])
            else:
                sum1 += layer * factorial(n - 1) / factorial(n - rep_count[layer])
        
        for k in range(n):
            final_sum += sum1 * 10 ** k
        
        results.append(int(final_sum))
    
    return results